graylog2:
  image: graylog2/server
  environment:
    - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
    - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    - GRAYLOG_REST_TRANSPORT_URI=http://graylog.rdi.at:12900
  links:
    - ${ELASTIC}:elasticsearch
    - ${MONGO}:mongo

lb:
  image: rancher/load-balancer-service
  ports:
    - ${GRAYLOG_WEB}:9000
    - ${GRAYLOG_INPUT}:12900
  labels:
    io.rancher.loadbalancer.target.graylog2: 9000=9000
    io.rancher.loadbalancer.target.graylog2: 12900=12900
  links:
    - graylog2:graylog2
  tty: true
  stdin_open: true
