.catalog:
  name: Atlassian
  version: v0.1.0
  description: |
    Atlassian Toolchain - Jira Confluence Bitbucket Bamboo
  minimum_rancher_version: v1.0.0
  questions:
    - variable: jira_host
      description: "Hostname of Jira instance reachable from external"
      label: "Jira Host"
      required: true
      default: "jira.example.com"
      type: string
    - variable: confluence_host
      description: "Hostname of Confluence instance reachable from external"
      label: "Confluence Host"
      required: true
      default: "confluence.example.com"
      type: string
    - variable: bitbucket_host
      description: "Hostname of Bitbucket instance reachable from external"
      label: "Confluence Host"
      required: true
      default: "bitbucket.example.com"
      type: string
    - variable: bamboo_host
      description: "Hostname of Bamboo instance reachable from external"
      label: "Confluence Host"
      required: true
      default: "bamboo.example.com"
      type: string
